<?php

/**
 * Standalone demo: build a typed MappingData, run it through the full
 * pipeline (Builder -> Generator -> Validator + AtomicWriter), and report
 * what landed on disk.
 *
 * Run from the repo root:
 *
 *   php examples/standalone/generate.php
 *
 * Output: a generated XRechnung 3.0 XML at out/Demo-Invoice-001.xml,
 * plus a one-line PASS / FAIL summary on the validator verdict.
 */

declare(strict_types=1);

require __DIR__ . '/../../vendor/autoload.php';

use XrechnungKit\Builder\XRechnungBuilder;
use XrechnungKit\Mapping\Address;
use XrechnungKit\Mapping\Contact;
use XrechnungKit\Mapping\DocumentMeta;
use XrechnungKit\Mapping\DocumentTotals;
use XrechnungKit\Mapping\LineItem;
use XrechnungKit\Mapping\MappingData;
use XrechnungKit\Mapping\Money;
use XrechnungKit\Mapping\Party;
use XrechnungKit\Mapping\PaymentMeans;
use XrechnungKit\Mapping\TaxBreakdown;
use XrechnungKit\Mapping\TaxId;
use XrechnungKit\XRechnungGenerator;
use XrechnungKit\XRechnungInvoiceTypeCode;
use XrechnungKit\XRechnungTaxCategory;
use XrechnungKit\XRechnungValidator;

$lines = [
    new LineItem(
        id: '1',
        description: 'Senior consulting hour, May 2026',
        quantity: '24',
        unitCode: 'HUR',
        unitPrice: Money::eur('150.00'),
        lineTotal: Money::eur('3600.00'),
        taxCategory: XRechnungTaxCategory::STANDARD_RATE,
        taxPercent: '19.00',
        name: 'Beratungsstunde Senior',
    ),
    new LineItem(
        id: '2',
        description: 'Cloud infrastructure surcharge',
        quantity: '1',
        unitCode: 'MON',
        unitPrice: Money::eur('420.00'),
        lineTotal: Money::eur('420.00'),
        taxCategory: XRechnungTaxCategory::STANDARD_RATE,
        taxPercent: '19.00',
        name: 'Hosting Mai 2026',
    ),
];

$mapping = MappingData::standardInvoice(
    meta: new DocumentMeta(
        invoiceNumber: 'Demo-Invoice-001',
        type: XRechnungInvoiceTypeCode::COMMERCIAL_INVOICE,
        issueDate: new DateTimeImmutable('2026-05-09'),
        currency: 'EUR',
        dueDate: new DateTimeImmutable('2026-06-08'),
        buyerReference: '04011000-12345-67',
        note: 'Demo invoice generated by examples/standalone/generate.php',
    ),
    seller: Party::business(
        name: 'Beispiel Lieferant GmbH',
        address: new Address(
            street: 'Lieferantenstrasse 1',
            city: 'Berlin',
            zip: '10115',
            countryCode: 'DE',
        ),
        taxId: TaxId::vatId('DE123456789'),
        contact: new Contact(
            name: 'Anna Beispiel',
            phone: '+49 30 12345678',
            email: 'billing@example-supplier.de',
        ),
        endpointEmail: 'billing@example-supplier.de',
    ),
    buyer: Party::publicAdministration(
        name: 'Bundesamt fuer Beispielzwecke',
        address: new Address(
            street: 'Behoerdenweg 7',
            city: 'Bonn',
            zip: '53113',
            countryCode: 'DE',
            additionalStreet: 'Haus 2',
        ),
        leitwegId: '04011000-12345-67',
        contact: new Contact(
            name: 'Bernd Beispiel',
            phone: '+49 228 87654321',
            email: 'einkauf@example-buyer.de',
        ),
        endpointEmail: 'einkauf@example-buyer.de',
    ),
    lines: $lines,
    taxes: [
        new TaxBreakdown(
            category: XRechnungTaxCategory::STANDARD_RATE,
            percent: '19.00',
            taxableAmount: Money::eur('4020.00'),
            taxAmount: Money::eur('763.80'),
        ),
    ],
    payment: [
        PaymentMeans::sepaCreditTransfer(
            iban: 'DE12500105170648489890',
            bic: 'INGDDEFFXXX',
            accountName: 'Beispiel Lieferant GmbH',
            paymentReference: 'Demo-Invoice-001',
        ),
    ],
    totals: new DocumentTotals(
        lineNet: Money::eur('4020.00'),
        taxableAmount: Money::eur('4020.00'),
        taxAmount: Money::eur('763.80'),
        payable: Money::eur('4783.80'),
    ),
);

$outputDir = __DIR__ . '/out';
if (!is_dir($outputDir) && !mkdir($outputDir, 0o755, true) && !is_dir($outputDir)) {
    fwrite(STDERR, "Could not create output directory: {$outputDir}\n");
    exit(1);
}
$targetPath = $outputDir . '/Demo-Invoice-001.xml';

$entity = XRechnungBuilder::buildEntity($mapping);
$generator = new XRechnungGenerator($entity);
$finalPath = $generator->generateXRechnung($targetPath);

$validator = new XRechnungValidator();
$isValid = $validator->validate($finalPath);

$invoiceNumber = $mapping->meta->invoiceNumber;
$payable = $mapping->totals->payable->amount . ' ' . $mapping->totals->payable->currency;
$lineCount = count($mapping->lines);

echo "Generated: {$finalPath}\n";
echo "Invoice:   {$invoiceNumber}, {$lineCount} lines, payable {$payable}\n";
echo 'Validator: ' . ($isValid ? 'PASS (UBL XSD valid)' : 'FAIL (lands at *_invalid.xml)') . "\n";

if (!$isValid) {
    echo "\nValidation errors:\n";
    foreach ($validator->getErrors() as $error) {
        echo "  - {$error}\n";
    }
    exit(1);
}

exit(0);
